#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

# User configuration

export PATH="./node_modules/.bin:$HOME/.rvm/bin:$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/git/bin"

# Don't error if globbing fails; just leave the globbing chars in.
setopt nonomatch

# Preferred editor for local and remote sessions
export EDITOR='mvim -f'
export PYOPEN_CMD='mvim -f'

# Python configuration
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP="$HOME/.pythonrc.py"

# virtualenvwrapper and pip
if [ `id -u` != '0' ]; then
  export VIRTUAL_ENV_DISABLE_PROMPT=1
  export WORKON_HOME=$HOME/.virtualenvs
  export PIP_VIRTUALENV_BASE=$WORKON_HOME
  export PIP_REQUIRE_VIRTUALENV=true
  export PIP_RESPECT_VIRTUALENV=true
fi

# AWS tooling
export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.6.12.0/libexec"
export JAVA_HOME="$(/usr/libexec/java_home)"
export AWS_RDS_HOME="/usr/local/Cellar/rds-command-line-tools/1.12.002/libexec"

# Load local configuration if available
if [ -e "$HOME/.local-bashrc" ]; then
  source "$HOME/.local-bashrc"
fi

eval "$(hub alias -s)"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# if [ -e ~/.zsh-extras/zsh-autosuggestions ]; then
# 	# Setup zsh-autosuggestions
# 	source ~/.zsh-extras/zsh-autosuggestions/autosuggestions.zsh

# 	# Enable autosuggestions automatically
# 	zle-line-init() {
# 	    zle autosuggest-start
# 	}
# 	zle -N zle-line-init

# 	# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# 	# zsh-autosuggestions is designed to be unobtrusive)
# 	bindkey '^T' autosuggest-toggle
# fi
